routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { #funcion anonima que devuelve una vista, se deja el nombre de la vista si el .blade.php
    return view('welcome');
}); #ya no se ocupa 
/*
#nota:para devolver una vista que esta dentro de una carpeta se hace .. carpeta.nombredelavista


#ejemplo
#ruta de tip get -> prueba es el nombre y  le estoy pasando un argumento a la ruta
Route::get('prueba/{nombre}', function ($nombre){
    echo "Hola ".$nombre;
});

#ejemplo
#vamos a usasar un prefijo esto quiere decir que la ruta seria ../pruebas/prueba/algo
Route::prefix('pruebas')->group(function () {
    Route::get('prueba/{nombre}', function ($nombre){
        echo "Hola ".$nombre;
    });

    Route::get('prueba2/{nombre}', function ($nombre){
        echo "Hola ".$nombre;
    });

    Route::get('prueba3/{id}','ControladorPrueba@traerLibro')->name('traerLibros');
});
*/

Auth::routes();

Route::get('/administrador', 'HomeController@index')->name('administrador')->middleware('auth');
Route::get('/trabajador', 'HomeController@index2')->name('trabajador')->middleware('auth'); 
Route::get('/','ControladorInicio@Index')->name('visiante.index');

/*
    debemos explicar lo que hace resource
    basicamente nos crea un a serie de rutas del tipo rest full 
    nos crea ControladorUsuarios@index, ..@store , ..@create, ..@destroy , .. @update , ..@show, ..@update , ..@edit
    entonces tenemos que crear estos métodos en el controlador correspondiente :D 
     o hacer make:controller nombrecontrolador --resource
*/

Route::middleware('auth')->group(function () {
    Route::prefix('administrador')->group(function(){

        Route::resource('usuarios','ControladorUsuarios');
        Route::get('usuarios/{id}/destroy', 'ControladorUsuarios@destroy')->name('usuarios.destroy');
        
        Route::resource('estados','ControladorEstados');
        Route::get('estados/{id}/destroy', 'ControladorEstados@destroy')->name('estados.destroy');

        Route::resource('editoriales','ControladorEditoriales');
        Route::get('editoriales/{id}/destroy', 'ControladorEditoriales@destroy')->name('editoriales.destroy');
        
        Route::resource('categorias','ControladorCategorias');
        Route::get('categorias/{id}/destroy', 'ControladorCategorias@destroy')->name('categorias.destroy');
        
        Route::resource('idiomas','ControladorIdiomas');
        Route::get('idiomas/{id}/destroy', 'ControladorIdiomas@destroy')->name('idiomas.destroy');

        Route::resource('autores','ControladorAutores');
        Route::get('autores/{id}/destroy', 'ControladorAutores@destroy')->name('autores.destroy');
        
        Route::resource('libros','ControladorLibros');
        Route::get('libros/{id}/destroy', 'ControladorLibros@destroy')->name('libros.destroy');

        Route::resource('trabajadores','ControladorTrabajadores');
        Route::get('trabajadores/{id}/destroy', 'ControladorTrabajadores@destroy')->name('trabajadores.destroy');

        Route::resource('correost','ControladorCorreoT');
        Route::get('correost/{id}/destroy', 'ControladorCorreoT@destroy')->name('correost.destroy');
        
        Route::resource('telefonost','ControladorTelefonoT');
        Route::get('telefonost/{id}/destroy', 'ControladorTelefonoT@destroy')->name('telefonost.destroy');

        Route::resource('direccionest','ControladorDireccionT');
        Route::get('direccionest/{id}/destroy', 'ControladorDireccionT@destroy')->name('direccionest.destroy');

        Route::resource('clientes','ControladorClientes');
        Route::get('clientes/{id}/destroy', 'ControladorClientes@destroy')->name('clientes.destroy');

        Route::resource('correosc','ControladorCorreoC');
        Route::get('correosc/{id}/destroy', 'ControladorCorreoC@destroy')->name('correosc.destroy');

        Route::resource('telefonosc','ControladorTelefonoC');
        Route::get('telefonosc/{id}/destroy', 'ControladorTelefonoC@destroy')->name('telefonosc.destroy');

        Route::resource('direccionesc','ControladorDireccionC');
        Route::get('direccionesc/{id}/destroy', 'ControladorDireccionC@destroy')->name('direccionesc.destroy');

        Route::resource('pagos','ControladorPagos');
        Route::get('pagos/{id}/destroy', 'ControladorPagos@destroy')->name('pagos.destroy');

        Route::resource('distribuidores','ControladorDistribuidores');
        Route::get('distribuidores/{id}/destroy', 'ControladorDistribuidores@destroy')->name('distribuidores.destroy');
    });

    Route::prefix('trabajador')->group(function(){

        Route::resource('arriendos','ControladorArriendo');
        Route::resource('devoluciones','ControladorDevolucion');
        Route::post('devoluciones/search', 'ControladorDevolucion@search')->name('devoluciones.search');
        Route::get('devoluciones/results/{id}', 'ControladorDevolucion@results')->name('devoluciones.results');

    });
    
});

app/Libro.php
<?php

namespace App;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;

class Libro extends Model
{

    use Notifiable;
    protected $table = "libro";
   # protected $primary_key = "n_serie";
    #protected $incrementing = false;

    protected $fillable = [

        'id',
        'isbn',
        'titulo',
        'n_paginas',
        'p_refrencia',
        'año_publicacion',
        'estado_id'
    ];
    #protected $hidden = ['id'];


        #relaciones
        #1-1 con estado
    public function estado()
        {

            return $this->belongsTo('App\Estado');
           

        }

    # muchos - muchos con autores

    public function autores()
        {

            return $this->belongsToMany('App\Autor');

        }
    #muchos - muchos con idiomas
    public function idiomas(){


            return $this->belongsToMany('App\Idioma');
    }
    #muchos a muchos con cotegoria
    public function categorias(){

        return $this->belongsToMany('App\Categoria');

    }

    public function editoriales(){

        return $this->belongsToMany('App\Editorial');
    }

    public function detalle_compra(){

        return $this->belongsTo('App\Detalle_compra');
    }

    public function arriendos(){

        return $this->hasMany('App\Arriendo_libro');
    }


     #función que permite crear un buscador usando SCOPE
     public function scopeSearch($query, $name) #segundo parámetro es el que se manda

     {
         return $query->where('titulo','LIKE',"%$name%");
 
     }
         public function scopeSearchTag($query, $name)
     {
 
         return $query->where('titulo','=',$name);
     }

}

resources/views/administrador/libro/create.blade.php
@extends('administrador.main')

@section('title','Crear un nuevo Libro')

@section('content')

    		<div class="panel panel-default">
				<div class="panel-heading">Nuevo libro</div>
					<div class="panel-body">
						<div class="col-md-12">
                                {!! Form::open(['route' => 'libros.store', 'method' => 'POST']) !!}
                                    <div class="form-group">
                                        {!! Form::label('isbn','Isbn')!!}
                                        {!! Form::text('isbn',Null,['class' => 'form-control', 'placeholder' => 'mínimo 10 dígitos', 'required'])!!}
                                    </div>

                                    <div class="form-group">
                                        {!! Form::label('titulo','Título')!!}
                                        {!! Form::text('titulo',Null,['class' => 'form-control', 'placeholder' => 'Título completo del libro','required'])!!}
                                    </div>

                                    <div class="form-group">
                                        {!! Form::label('n_paginas','Número de Páginas')!!}
                                        {!! Form::number('n_paginas',Null,['class' => 'form-control', 'placeholder' => '','min' =>'0','required'])!!}
                                    </div>
                                    <div class="form-group">
                                        {!! Form::label('p_refrencia','Precio de Referencia')!!}
                                        {!! Form::number('p_refrencia',Null,['class' => 'form-control', 'placeholder' => '','min' =>'0','required'])!!}
                                    </div>
                                    <div class="form-group">
                                        {!! Form::label('año_publicacion','Año de Publicación')!!}
                                        {!! Form::number('año_publicacion',Null,['class' => 'form-control', 'placeholder' => '','min' =>'0','required'])!!}
                                    </div>
                                    <div class="form-group">
			                            {!! Form::label('estado_id', 'Estados') !!}
			                            {!! Form::select('estado_id', $estados,NULL,['class' => 'form-control','placeholder' => 'Seleccione una opción...','required'])!!}
		                            </div>

                                    <div class="form-group">
			                            {!! Form::label('editoriales', 'Editoriales') !!}
			                            {!! Form::select('editoriales[]', $editoriales,NULL,['class' => 'form-control chosen-select','multiple','required'])!!}
		                            </div>
                                    <div class="form-group">
			                            {!! Form::label('categorias', 'Categorías') !!}
			                            {!! Form::select('categorias[]', $categorias,NULL,['class' => 'form-control chosen-select','multiple','required'])!!}
		                            </div>
                                    <div class="form-group">
			                            {!! Form::label('idiomas', 'Idiomas') !!}
			                            {!! Form::select('idiomas[]', $idiomas,NULL,['class' => 'form-control chosen-select','multiple','required'])!!}
		                            </div>
                                    <div class="form-group">
			                            {!! Form::label('autores', 'Autores') !!}
			                            {!! Form::select('autores[]', $autores,NULL,['class' => 'form-control chosen-select','multiple','required'])!!}
		                            </div>
                                    <div class="form-group">
                                        
                                        {!! Form::submit('Agregar',['class' => 'btn btn-success btn-lg'])!!}

                                    </div>		

                                {!! Form::close() !!}

							
                        </div>
					</div>
				</div>
			</div><!-- /.panel-->
    

@endsection

@section('js')

<script type="text/javascript">
	
	$(".chosen-select").chosen({

		placeholder_text_multiple: 'seleccione múltiples opciones',
		no_results_text: "No se encontraron coincidencias!!"
	});
</script>

@endsection

resources/views/administrador/libro/edit.blade.php
@extends('administrador.main')

@section('title','Editar Libro: '.$libro->titulo )

@section('content')

    		<div class="panel panel-default">
				<div class="panel-heading">Editar Libro</div>
					<div class="panel-body">
						<div class="col-md-12">
                                {!! Form::open(['route' => ['libros.update',$libro], 'method' => 'PUT']) !!}
                                <div class="form-group">
                                        {!! Form::label('isbn','Isbn')!!}
                                        {!! Form::text('isbn',$libro->isbn,['class' => 'form-control', 'required'])!!}
                                    </div>

                                    <div class="form-group">
                                        {!! Form::label('titulo','Título')!!}
                                        {!! Form::text('titulo',$libro->titulo,['class' => 'form-control','required'])!!}
                                    </div>

                                    <div class="form-group">
                                        {!! Form::label('n_paginas','Número de Páginas')!!}
                                        {!! Form::number('n_paginas',$libro->n_paginas,['class' => 'form-control','min' =>'0','required'])!!}
                                    </div>
                                    <div class="form-group">
                                        {!! Form::label('p_refrencia','Precio de Referencia')!!}
                                        {!! Form::number('p_refrencia',$libro->p_refrencia,['class' => 'form-control','min' =>'0','required'])!!}
                                    </div>
                                    <div class="form-group">
                                        {!! Form::label('año_publicacion','Año de Publicación')!!}
                                        {!! Form::number('año_publicacion',$libro->año_publicacion,['class' => 'form-control','min' =>'0','required'])!!}
                                    </div>
                                    <div class="form-group">
			                            {!! Form::label('estado_id', 'Estado') !!}
			                            {!! Form::select('estado_id', $estados,$libro->estado->id,['class' => 'form-control','required'])!!}
		                            </div>

                                    <div class="form-group">
			                            {!! Form::label('editoriales', 'Editoriales') !!}
			                            {!! Form::select('editoriales[]', $editoriales,$mis_editoriales,['class' => 'form-control chosen-select','multiple','required'])!!}
		                            </div>
                                    <div class="form-group">
			                            {!! Form::label('categorias', 'Categorías') !!}
			                            {!! Form::select('categorias[]', $categorias,$mis_categorias,['class' => 'form-control chosen-select','multiple','required'])!!}
		                            </div>
                                    <div class="form-group">
			                            {!! Form::label('idiomas', 'Idiomas') !!}
			                            {!! Form::select('idiomas[]', $idiomas,$mis_idiomas,['class' => 'form-control chosen-select','multiple','required'])!!}
		                            </div>
                                    <div class="form-group">
			                            {!! Form::label('autores', 'Autores') !!}
			                            {!! Form::select('autores[]', $autores,$mis_autores,['class' => 'form-control chosen-select','multiple','required'])!!}
		                            </div>
                                    <div class="form-group">
                                        
                                        {!! Form::submit('Editar',['class' => 'btn btn-success btn-lg'])!!}

                                    </div>		

                                {!! Form::close() !!}

							
                        </div>
					</div>
				</div>
			</div><!-- /.panel-->
    

@endsection


@section('js')

<script type="text/javascript">
	
	$(".chosen-select").chosen({

		placeholder_text_multiple: 'seleccione múltiples opciones',
		no_results_text: "No se encontraron coincidencias!!"
	});
</script>

@endsection

resources/views/administrador/libro/index.blade.php
@extends('administrador.main')

@section('title','Mantenedor de Libros')

@section('content')


    {!! Form::open(['route' => 'libros.index', 'method' => 'GET', 'class' => 'navbar-form pull-right']) !!}
	<div class="input-group ">
		{!! Form::Text('name',NULL, ['class'=> 'form-control', 'placeholder' => 'Buscar por titulo..', 'aria-describedby' =>'search']) !!}
		<span class="input-group-addon" id="search"><span class="fa fa-search"></span></span>
	</div>
    {!! Form::close() !!}
<div class="container">
	<a href="{{ route('libros.create')}}" class="btn btn-info btn-lg"><i class="fa fa-plus"></i> Libro</a>
</div>	
<div class="panel panel-default">
	<div class="panel-heading">Libros</div>
		<div class="panel-body">
			<div class="col-md-12 table-responsive">
                <table class="table table-bordered">
                <thead>
                        <th >ID</th>
                        <th  >ISBN</th>
                        <th class="col-sm-3">Título</th>

                        <th>precio</th>

                        <th class="col-sm-2">idiomas</th>
                        <th>Editoriales</th>
                        <th class="col-sm-2">Autores</th>
                        <th class="col-sm-2">Categorías</th>
                        <th>Estado</th>

                      <th class="col-sm-3">Acción</th>
                </thead>
                <tbody>
                       @foreach($libros as $libro)
                            <tr>
                                <td>{{ $libro->id }}</td>
                                <td>{{ $libro->isbn }}</td>
                                <td>{{ $libro->titulo }}</td>
 
                                <td>{{ $libro->p_refrencia }}</td>

                                <td>
                                    
                                    @foreach($libro->idiomas as $idioma)
                                    <li>{{ $idioma->idioma}}</li>
                                    @endforeach
                                </td>

                                 <td> 
                                    @foreach($libro->editoriales as $editorial)
                                    <li>{{ $editorial->nombre_editorial}}</li>
                                    @endforeach
                                </td>
                                 <td>
                                    @foreach($libro->autores as $autor)
                                    <li>{{ $autor->nombre}}</li>
                                    @endforeach
                                </td>
                                <td>
                                    @foreach($libro->categorias as $categoria)
                                    <li>{{ $categoria->categoria}}</li>
                                    @endforeach
                                </td>

                                <td>{{ $libro->estado->estado }}</td>

                                <td> 
                                    <a href="{{route('libros.edit',$libro->id)}}" class="btn btn-success"><i class="fa fa-pencil-square"></i></a>
                                    <a href="{{ route('libros.destroy',$libro->id)}}" onclick ="return confirm('¿Seguro que desea elminiar este registro?')" class="btn btn-danger" ><i class="fa fa-trash"></i></a>
                                    
                                </td>
                            </tr>

                        @endforeach
                </tbody>
                </table>
                {{ $libros->render() }}<!--es para a paginación-->
                
            </div>
        </div>
    </div>
@endsection