routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { #funcion anonima que devuelve una vista, se deja el nombre de la vista si el .blade.php
    return view('welcome');
}); #ya no se ocupa 
/*
#nota:para devolver una vista que esta dentro de una carpeta se hace .. carpeta.nombredelavista


#ejemplo
#ruta de tip get -> prueba es el nombre y  le estoy pasando un argumento a la ruta
Route::get('prueba/{nombre}', function ($nombre){
    echo "Hola ".$nombre;
});

#ejemplo
#vamos a usasar un prefijo esto quiere decir que la ruta seria ../pruebas/prueba/algo
Route::prefix('pruebas')->group(function () {
    Route::get('prueba/{nombre}', function ($nombre){
        echo "Hola ".$nombre;
    });

    Route::get('prueba2/{nombre}', function ($nombre){
        echo "Hola ".$nombre;
    });

    Route::get('prueba3/{id}','ControladorPrueba@traerLibro')->name('traerLibros');
});
*/

Auth::routes();

Route::get('/administrador', 'HomeController@index')->name('administrador')->middleware('auth');
Route::get('/trabajador', 'HomeController@index2')->name('trabajador')->middleware('auth'); 
Route::get('/','ControladorInicio@Index')->name('visiante.index');

/*
    debemos explicar lo que hace resource
    basicamente nos crea un a serie de rutas del tipo rest full 
    nos crea ControladorUsuarios@index, ..@store , ..@create, ..@destroy , .. @update , ..@show, ..@update , ..@edit
    entonces tenemos que crear estos métodos en el controlador correspondiente :D 
     o hacer make:controller nombrecontrolador --resource
*/

Route::middleware('auth')->group(function () {
    Route::prefix('administrador')->group(function(){

        Route::resource('usuarios','ControladorUsuarios');
        Route::get('usuarios/{id}/destroy', 'ControladorUsuarios@destroy')->name('usuarios.destroy');
        
        Route::resource('estados','ControladorEstados');
        Route::get('estados/{id}/destroy', 'ControladorEstados@destroy')->name('estados.destroy');

        Route::resource('editoriales','ControladorEditoriales');
        Route::get('editoriales/{id}/destroy', 'ControladorEditoriales@destroy')->name('editoriales.destroy');
        
        Route::resource('categorias','ControladorCategorias');
        Route::get('categorias/{id}/destroy', 'ControladorCategorias@destroy')->name('categorias.destroy');
        
        Route::resource('idiomas','ControladorIdiomas');
        Route::get('idiomas/{id}/destroy', 'ControladorIdiomas@destroy')->name('idiomas.destroy');

        Route::resource('autores','ControladorAutores');
        Route::get('autores/{id}/destroy', 'ControladorAutores@destroy')->name('autores.destroy');
        
        Route::resource('libros','ControladorLibros');
        Route::get('libros/{id}/destroy', 'ControladorLibros@destroy')->name('libros.destroy');

        Route::resource('trabajadores','ControladorTrabajadores');
        Route::get('trabajadores/{id}/destroy', 'ControladorTrabajadores@destroy')->name('trabajadores.destroy');

        Route::resource('correost','ControladorCorreoT');
        Route::get('correost/{id}/destroy', 'ControladorCorreoT@destroy')->name('correost.destroy');
        
        Route::resource('telefonost','ControladorTelefonoT');
        Route::get('telefonost/{id}/destroy', 'ControladorTelefonoT@destroy')->name('telefonost.destroy');

        Route::resource('direccionest','ControladorDireccionT');
        Route::get('direccionest/{id}/destroy', 'ControladorDireccionT@destroy')->name('direccionest.destroy');

        Route::resource('clientes','ControladorClientes');
        Route::get('clientes/{id}/destroy', 'ControladorClientes@destroy')->name('clientes.destroy');

        Route::resource('correosc','ControladorCorreoC');
        Route::get('correosc/{id}/destroy', 'ControladorCorreoC@destroy')->name('correosc.destroy');

        Route::resource('telefonosc','ControladorTelefonoC');
        Route::get('telefonosc/{id}/destroy', 'ControladorTelefonoC@destroy')->name('telefonosc.destroy');

        Route::resource('direccionesc','ControladorDireccionC');
        Route::get('direccionesc/{id}/destroy', 'ControladorDireccionC@destroy')->name('direccionesc.destroy');

        Route::resource('pagos','ControladorPagos');
        Route::get('pagos/{id}/destroy', 'ControladorPagos@destroy')->name('pagos.destroy');

        Route::resource('distribuidores','ControladorDistribuidores');
        Route::get('distribuidores/{id}/destroy', 'ControladorDistribuidores@destroy')->name('distribuidores.destroy');
    });

    Route::prefix('trabajador')->group(function(){

        Route::resource('arriendos','ControladorArriendo');
        Route::resource('devoluciones','ControladorDevolucion');
        Route::post('devoluciones/search', 'ControladorDevolucion@search')->name('devoluciones.search');
        Route::get('devoluciones/results/{id}', 'ControladorDevolucion@results')->name('devoluciones.results');

    });
    
});

app/Trabajador.php
<?php

namespace App;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;

class Trabajador extends Model
{
    use notifiable;

    protected $table = "trabajador";

    protected $fillable =[
        'id',
        'rut',
        'nombre',
        'apellido_paterno',
        'apellido_materno',
        'anio_contrato'
    ];

    #protected $hidden = ['id'];
    #un trabajador puede tener muchos correos, y un correo puede tener solo una persona, es unico
    public function correos(){

        return $this->hasMany('App\CorreoT');
    }

    public function direcciones(){

        return $this->hasMany('App\DireccionT');
    }

    public function telefonos(){

        return $this->hasMany('App\TelefonoT');
    }

    public function boletas(){

        return $this->hasMany('App\Boleta');
    }

    public function arriendos(){

        return $this->hasMany('App\Arriendo_libro');
    }

     #función que permite crear un buscador usando SCOPE
     public function scopeSearch($query, $name) #segundo parámetro es el que se manda

     {
         return $query->where('nombre','LIKE',"%$name%");
 
     }
         public function scopeSearchTag($query, $name)
     {
 
         return $query->where('nombre','=',$name);
     }

}

resources/views/administrador/trabajador/create.blade.php
@extends('administrador.main')

@section('title','Crear un nuevo trabajador')

@section('content')

    		<div class="panel panel-default">
				<div class="panel-heading">Nuevo trabajador</div>
					<div class="panel-body">
						<div class="col-md-12">
                                {!! Form::open(['route' => 'trabajadores.store', 'method' => 'POST']) !!}
                                <div class="form-group">
                                        {!! Form::label('rut','RUT')!!}
                                        {!! Form::text('rut',Null,['class' => ['form-control','rut'], 'placeholder' => '11.111.111-1', 'required'])!!}
                                    </div>
                                    <div class="form-group">
                                        {!! Form::label('nombre','Nombre')!!}
                                        {!! Form::text('nombre',Null,['class' => 'form-control', 'placeholder' => 'Ambos nombres', 'required'])!!}
                                    </div>

                                    <div class="form-group">
                                        {!! Form::label('apellido_paterno','Apellido Paterno')!!}
                                        {!! Form::text('apellido_paterno',Null,['class' => 'form-control', 'placeholder' => ''])!!}
                                    </div>

                                    <div class="form-group">
                                        {!! Form::label('apellido_materno','Apellido Materno')!!}
                                        {!! Form::text('apellido_materno',Null,['class' => 'form-control', 'placeholder' => ''])!!}
                                    </div>
                                    <div class="form-group">
                                        {!! Form::label('anio_contrato','Año inicio de contrato')!!}
                                        {!! Form::text('anio_contrato',Null,['class' => 'form-control', 'placeholder' => ''])!!}
                                    </div>
                                    <div class="form-group">
                                        
                                        {!! Form::submit('Agregar',['class' => 'btn btn-success btn-lg'])!!}

                                    </div>		

                                {!! Form::close() !!}

							
                        </div>
					</div>
				</div>
			</div><!-- /.panel-->
    
@endsection


@section('js')

<script type="text/javascript">
	
$(".rut")
  .rut({formatOn: 'keyup', validateOn: 'keyup'})
  .on('rutInvalido', function(){ 
    $(this).parents(".control-group").addClass("error")
  })
  .on('rutValido', function(){ 
$(this).parents(".control-group").removeClass("error")
  });
</script>

@endsection

resources/views/administrador/trabajador/edit.blade.php
@extends('administrador.main')

@section('title','Editar trabajador: '.$trabajador->nombre.' '.$trabajador->apellido_paterno)

@section('content')

    		<div class="panel panel-default">
				<div class="panel-heading">Editar trabajador</div>
					<div class="panel-body">
						<div class="col-md-12">
                        {!! Form::open(['route' => ['trabajadores.update',$trabajador], 'method' => 'PUT']) !!}
                                    <div class="form-group">
                                        {!! Form::label('rut','RUT')!!}
                                        {!! Form::text('rut',$trabajador->rut,['class' => ['form-control','rut'],'required'])!!}
                                    </div>
                                    
                                    <div class="form-group">
                                        {!! Form::label('nombre','Nombre')!!}
                                        {!! Form::text('nombre',$trabajador->nombre,['class' => 'form-control', 'required'])!!}
                                    </div>

                                    <div class="form-group">
                                        {!! Form::label('apellido_paterno','Apellido Paterno')!!}
                                        {!! Form::text('apellido_paterno',$trabajador->apellido_paterno,['class' => 'form-control'])!!}
                                    </div>

                                    <div class="form-group">
                                        {!! Form::label('apellido_materno','Apellido Materno')!!}
                                        {!! Form::text('apellido_materno',$trabajador->apellido_materno,['class' => 'form-control'])!!}
                                    </div>
                                    <div class="form-group">

                                    <div class="form-group">
                                        {!! Form::label('anio_contrato','Año inico de contrato')!!}
                                        {!! Form::text('anio_contrato',$trabajador->anio_contrato,['class' => 'form-control'])!!}
                                    </div>
                                    <div class="form-group">
                                        
                                        {!! Form::submit('Editar',['class' => 'btn btn-success btn-lg'])!!}

                                    </div>		

                                {!! Form::close() !!}

                        </div>
					</div>
				</div>
			</div><!-- /.panel-->

    @endsection


@section('js')

        <script type="text/javascript">
            
        $(".rut")
        .rut({formatOn: 'keyup', validateOn: 'keyup'})
        .on('rutInvalido', function(){ 
            $(this).parents(".control-group").addClass("error")
        })
        .on('rutValido', function(){ 
        $(this).parents(".control-group").removeClass("error")
        });
        </script>

@endsection

resources/views/administrador/trabajador/index.blade.php
@extends('administrador.main')

@section('title','Mantenedor de Trabajadores')

@section('content')


    {!! Form::open(['route' => 'trabajadores.index', 'method' => 'GET', 'class' => 'navbar-form pull-right']) !!}
	<div class="input-group ">
		{!! Form::Text('name',NULL, ['class'=> 'form-control', 'placeholder' => 'Buscar por nombre..', 'aria-describedby' =>'search']) !!}
		<span class="input-group-addon" id="search"><span class="fa fa-search"></span></span>
	</div>
    {!! Form::close() !!}
<div class="container">
	<a href="{{ route('trabajadores.create')}}" class="btn btn-info btn-lg"><i class="fa fa-plus"></i> Trabajador</a>
</div>	
<div class="panel panel-default">
	<div class="panel-heading">Trabajadores</div>
		<div class="panel-body">
			<div class="col-md-12 table-responsive">
                <table class="table table-bordered">
                <thead>
                        <th>ID</th>
                        <th>RUT</th>
                        <th >Nombres</th>
                        <th>Apellidos</th>
                        <th >Año inicio de contrato</th>
                        <th class="col-md-3">Emails</th>
                        <th class="col-md-3">Teléfonos</th>
                        <th class="col-md-3">direcciones</th>
                        <th class="col-md-2">Acción</th>
                </thead>
                <tbody>
                        @foreach($trabajadores as $trabajador)
                            <tr>
                                <td>{{ $trabajador->id }}</td>
                                <td>{{ $trabajador->rut}}</td>
                                <td>{{ $trabajador->nombre }}</td>
                                <td>{{ $trabajador->apellido_paterno.' '.$trabajador->apellido_materno}}</td>
                                
                                <td>{{ $trabajador->anio_contrato }}</td>

                                <td>                                 
                                @foreach($trabajador->correos as $correo)
                                    <li>{{ $correo->correo}}</li>
                                    @endforeach
                                </td>
                                
                                <td>                                 
                                @foreach($trabajador->telefonos as $telefono)
                                    <li>{{ $telefono->telefono}}</li>
                                    @endforeach
                                </td>
                                <td>                                 
                                @foreach($trabajador->direcciones as $direccion)
                                    <li>{{ $direccion->direccion}}</li>
                                    @endforeach
                                </td>
   
                                <td> 
                                    <a href="{{route('trabajadores.edit',$trabajador->id)}}" class="btn btn-success"><i class="fa fa-pencil-square"></i></a>
                                    <a href="{{ route('trabajadores.destroy',$trabajador->id)}}" onclick ="return confirm('¿Seguro que desea elminiar este registro?')" class="btn btn-danger" ><i class="fa fa-trash"></i></a>
                                    
                                </td>
                            </tr>

                        @endforeach
                </tbody>
                </table>
                {{ $trabajadores->render() }}<!--es para a paginación-->
            </div>
        </div>
    </div>
@endsection